### ISSUE TITLE
onMethodCall: send

### ISSUE THREAD

**Issue by Arlen0615** [applogik/unity_widget#3]
Hi,

Thanks for great work, I use this widget, and it worked on unity 2019 very well. 
(BTW, unity 2020 on Ubuntu hard to export 'suitable' IL2CPP)

I found one log keep output, does anyway to disable it?

**D/com.ahmadre.unity_widget.FlutterUnityView@467ecc5(12516): onMethodCall: send**

**Comment by Ahmadre** [comment]
> Hi,
> 
> 
> 
> Thanks for great work, I use this widget, and it worked on unity 2019 very well. 
> 
> (BTW, unity 2020 on Ubuntu hard to export 'suitable' IL2CPP)
> 
> 
> 
> I found one log keep output, does anyway to disable it?
> 
> 
> 
> **D/com.ahmadre.unity_widget.FlutterUnityView@467ecc5(12516): onMethodCall: send**

Thank you so much for your feedback 🙂 

sure I will disable that log. It's even unnecessary on Android side.

Will notify you here 👍

**Comment by Ahmadre** [comment]
Removed in 1.0.4 :)

**Comment by Arlen0615** [comment]
Still get onMethodCall: send in iOS, android is work
