### ISSUE TITLE
CocoaPods could not find compatible versions for pod "unity_widget"

### ISSUE THREAD

**Issue by Arlen0615** [applogik/unity_widget#4]
Hi, 

I follow the instruction to setup in iOS part, but I get following build error, any suggestion?

[!] CocoaPods could not find compatible versions for pod "unity_widget": In Podfile: unity_widget (from `.symlinks/plugins/unity_widget/ios`)

**Comment by Arlen0615** [comment]
Go To Xcode Pods -> Pod file, change 

platform :ios, '10.0' to platform :ios, '11.0'

It work for me.

**Comment by Ahmadre** [comment]
> Go To Xcode Pods -> Pod file, change 
> 
> 
> 
> platform :ios, '10.0' to platform :ios, '11.0'
> 
> 
> 
> It work for me.

Yup, I should have mention this. There're a lot of other new interface changes on ios side I have to mention in readme. It's a lot to be aware 😅.
