### ISSUE TITLE
FlutterUnityPlugin.m 'UnityFramework/UnityFramework.h' file not found

### ISSUE THREAD

**Issue by Arlen0615** [applogik/unity_widget#5]
Hi,

Some of iOS 14 issue, the app can not open if your debug cable unplug with iPhone, 
so I  use release build from related suggestion,
e.q. 
1.in xcode, Product -> Scheme -> Edit Sheme, changed Build Configuration from Debug to release,

2.flutter clean and flutter build ios --release 

and I get following error,

Lexical or Preprocessor Issue (Xcode): 'UnityFramework/UnityFramework.h' file not found
/Users/arlen/Desktop/development/flutter/.pub-cache/hosted/pub.dartlang.org/unity_widget-1.0.4/ios/Classes/FlutterUnityPlugin.m:2:8

I study related topic about **UnityFramework.h not found**, some of them add PostBuildProcess to Editor folder in Asset in unity project for MainAp/main.mm, but this is FlutterUnityPlugin.m.

**Comment by Ahmadre** [comment]
Are you using Flavors for your app?

**Comment by Ahmadre** [comment]
Please consider using: https://github.com/juicycleff/flutter-unity-view-widget
