### ISSUE TITLE
Unity blocking flutter (WebGL)

### ISSUE THREAD

**Issue by andybass** [applogik/unity_widget#7]
Hello - 

On WebGL, I'm able to render a Flutter widget (such as a button) over the UnityView widget, but I'm not able to interact with it - the UnityView seems to take precedence, and prevent the click. 

Any ideas on how to get that working?

Thanks!

**Comment by Ahmadre** [comment]
This is a Flutter Issue and not related to this Plugin.

But there's a workaround by Flutter Team itself: https://pub.dev/packages/pointer_interceptor
