### ISSUE TITLE
Requested NDK version 20.0.5594570 did not match the version 19.0.5232133

### ISSUE THREAD

**Issue by cancaglar** [applogik/unity_widget#8]
Unity's ndk version is not matching with requested ndk version so i tried to change build.gradle.ndkVersion to  19.0.5232133(unity ndk version) and I solved to error but when i build the app the screen is gray  but when i run the app i can use unity app inside the flutter. And when i change the unity's ndk path i can't build or export the project.  Any advice?

**Comment by Ahmadre** [comment]
Please consider using: https://github.com/juicycleff/flutter-unity-view-widget

I improved and solved this NDK stuff
